<?php
/**
 * The still that appears where the pointer is on the seek bar.
 *
 * Two halves worth checking, and the first is the parser. A storyboard is a
 * WebVTT file whose cues carry a sprite address with a `#xywh=` fragment, and
 * the files real tools produce are not tidy: comments, cue identifiers, NOTE
 * blocks, Windows line endings, timestamps with the hour left off. A parser
 * that only reads the shape one exporter happens to write is a feature that
 * works for whoever wrote the test and nobody else.
 *
 * The second is the cost. This exists to be free until it is used: the file is
 * not fetched, and the code that reads it is not downloaded, until a pointer
 * is actually on the bar. A reader who never scrubs pays nothing.
 */

require __DIR__ . '/bootstrap.php';

use ImaginaPlayer\Render\PlayerRenderer;

$root = dirname( __DIR__ );

$failures = 0;
function check( string $label, bool $ok, string $detail = '' ): void {
	global $failures;
	if ( ! $ok ) { $failures++; }
	echo ( $ok ? 'PASS  ' : 'FAIL  ' ) . $label . ( $ok || '' === $detail ? '' : "  [{$detail}]" ) . PHP_EOL;
}

echo PHP_EOL . '# It reaches the browser only when there is one' . PHP_EOL;

$renderer = new PlayerRenderer();

$with = $renderer->render(
	array(
		'src'        => 'https://cdn.example.com/clip.mp4',
		'storyboard' => 'https://cdn.example.com/board.vtt',
	)
);

check( 'a configured storyboard is handed over', str_contains( $with, 'board.vtt' ) );

$without = $renderer->render( array( 'src' => 'https://cdn.example.com/clip.mp4' ) );

check(
	'and a video without one carries an empty field, not a missing key',
	str_contains( $without, 'storyboard' ) && ! str_contains( $without, '.vtt' )
);

echo PHP_EOL . '# The parser, on files real tools write' . PHP_EOL;

$node = trim( (string) shell_exec( 'command -v node 2>/dev/null' ) );

if ( '' === $node ) {
	echo 'SKIP  no node; the parser was not exercised' . PHP_EOL;
} else {
	shell_exec(
		sprintf(
			'cd %s && npx tsc assets/src/frontend/storyboard.ts --outDir build/.board-check --module es2020 --target es2020 --moduleResolution bundler 2>&1',
			escapeshellarg( $root )
		)
	);

	$compiled = $root . '/build/.board-check/storyboard.js';

	if ( ! file_exists( $compiled ) ) {
		echo 'SKIP  the parser would not compile' . PHP_EOL;
	} else {
		/*
		 * Deliberately awkward: a header comment, a NOTE block, cue
		 * identifiers, Windows line endings on one cue, an hour-less timestamp,
		 * a cue with no fragment, and a cue whose tile has no size.
		 */
		$vtt = "WEBVTT - Generated by something\n\n"
			. "NOTE this file was made by a tool that likes notes\n\n"
			. "1\n00:00:00.000 --> 00:00:10.000\nsprite-0.jpg#xywh=0,0,160,90\n\n"
			. "2\r\n00:00:10.000 --> 00:00:20.000\r\nsprite-0.jpg#xywh=160,0,160,90\r\n\r\n"
			. "00:20.000 --> 00:30.000\nsprite-0.jpg#xywh=320,0,160,90\n\n"
			. "00:00:30.000 --> 00:00:40.000\nsprite-0.jpg\n\n"
			. "00:00:40.000 --> 00:00:50.000\nsprite-1.jpg#xywh=0,0,0,0\n\n"
			. "00:00:50.000 --> 00:01:00.000\n/wp-content/boards/sprite-1.jpg#xywh=0,90,160,90\n\n"
			/*
			 * Two tiles a storyboard has no business pointing at. The address
			 * ends up in a CSS url() in every visitor's browser, and a
			 * storyboard is set by whoever edits the post — so a data: tile is
			 * a way to load an arbitrary picture, and javascript: is kept out
			 * on principle even though CSS would not run it.
			 */
			. "00:01:00.000 --> 00:01:10.000\ndata:image/png;base64,iVBORw0KGgo=#xywh=0,0,160,90\n\n"
			. "00:01:10.000 --> 00:01:20.000\njavascript:alert(1)#xywh=0,0,160,90\n";

		$script = $root . '/build/.board-check.mjs';

		file_put_contents(
			$script,
			"import { parse } from '" . $compiled . "';\n"
			. 'const vtt = ' . wp_json_encode( $vtt ) . ";\n"
			. "const tiles = parse(vtt, 'https://example.test/boards/board.vtt');\n"
			. "console.log(JSON.stringify({ count: tiles.length, tiles }));\n"
		);

		$raw    = (string) shell_exec( 'node ' . escapeshellarg( $script ) . ' 2>/dev/null' );
		$parsed = json_decode( trim( $raw ), true );

		exec( 'rm -rf ' . escapeshellarg( $root . '/build/.board-check' ) . ' ' . escapeshellarg( $script ) );

		if ( ! is_array( $parsed ) ) {
			check( 'the parser ran', false, trim( $raw ) );
		} else {
			$tiles = (array) $parsed['tiles'];

			check( 'four usable cues out of eight', 4 === (int) $parsed['count'], (string) $parsed['count'] );
			check( 'a header and a NOTE block are not cues', 4 === (int) $parsed['count'] );

			$schemes = array_map(
				static fn( array $tile ): string => (string) parse_url( (string) ( $tile['url'] ?? '' ), PHP_URL_SCHEME ),
				$tiles
			);

			check(
				'a tile on a scheme the page is not on is dropped, not loaded',
				! in_array( 'data', $schemes, true ) && ! in_array( 'javascript', $schemes, true ),
				implode( ', ', $schemes )
			);

			check( 'the first tile starts at zero', 0.0 === (float) ( $tiles[0]['start'] ?? -1 ) );
			check( 'and names its place in the sprite', 0 === (int) ( $tiles[0]['x'] ?? -1 ) && 160 === (int) ( $tiles[0]['w'] ?? 0 ) );

			// The one with Windows line endings, which is most exports on Windows.
			check( 'a cue with CRLF line endings is read', 10.0 === (float) ( $tiles[1]['start'] ?? -1 ), wp_json_encode( $tiles[1]['start'] ?? null ) );
			check( 'and its tile is the second in the row', 160 === (int) ( $tiles[1]['x'] ?? -1 ) );

			// `00:20.000` rather than `00:00:20.000`, which is legal WebVTT.
			check( 'a timestamp with the hour left off is understood', 20.0 === (float) ( $tiles[2]['start'] ?? -1 ), wp_json_encode( $tiles[2]['start'] ?? null ) );

			// A cue with no `#xywh=` names a whole image, which this cannot place.
			check( 'a cue with no tile fragment is dropped', 4 === (int) $parsed['count'] );
			check( 'and one whose tile has no size', ! in_array( 0, array_column( $tiles, 'w' ), true ) );

			/*
			 * Relative addresses resolve against the file, not against the page:
			 * a storyboard in an uploads folder names its sprites beside itself.
			 */
			check(
				'a relative sprite resolves against the storyboard, not the page',
				'https://example.test/boards/sprite-0.jpg' === ( $tiles[0]['url'] ?? '' ),
				(string) ( $tiles[0]['url'] ?? '' )
			);

			check(
				'and an absolute path resolves against the site',
				'https://example.test/wp-content/boards/sprite-1.jpg' === ( $tiles[3]['url'] ?? '' ),
				(string) ( $tiles[3]['url'] ?? '' )
			);
		}
	}
}

echo PHP_EOL . '# It costs nothing until somebody drags the bar' . PHP_EOL;

function find_browser(): string {
	$candidates = array_filter(
		array_merge(
			array( (string) getenv( 'CHROMIUM_BIN' ) ),
			glob( '/opt/pw-browsers/chromium-*/chrome-linux/chrome' ) ?: array(),
			glob( '/opt/pw-browsers/chromium_headless_shell-*/chrome-linux/headless_shell' ) ?: array()
		)
	);

	foreach ( $candidates as $candidate ) {
		if ( '' !== $candidate && is_executable( $candidate ) ) {
			return $candidate;
		}
	}

	return '';
}

$browser = find_browser();

if ( '' === $browser ) {
	echo 'SKIP  no Chromium found; the preview was not driven' . PHP_EOL;
	echo PHP_EOL . ( $failures ? "{$failures} FAILURE(S)" : 'All checks passed.' ) . PHP_EOL;
	exit( $failures ? 1 : 0 );
}

$workdir = $root . '/build/.board-test';

if ( ! is_dir( $workdir ) ) {
	mkdir( $workdir, 0777, true );
}

foreach ( (array) glob( $root . '/build/*.{js,css}', GLOB_BRACE ) as $asset ) {
	copy( (string) $asset, $workdir . '/' . basename( (string) $asset ) );
}

// A real storyboard beside a real sprite, both served from the same folder.
file_put_contents(
	$workdir . '/board.vtt',
	"WEBVTT\n\n00:00:00.000 --> 00:00:50.000\nsprite.png#xywh=0,0,160,90\n\n"
	. "00:00:50.000 --> 00:01:40.000\nsprite.png#xywh=160,0,160,90\n"
);

// A two-tile sprite, written by hand so nothing has to be fetched.
$png = static function ( int $w, int $h ): string {
	$chunk = static fn( string $type, string $data ): string =>
		pack( 'N', strlen( $data ) ) . $type . $data . pack( 'N', crc32( $type . $data ) );

	$raw = '';

	for ( $y = 0; $y < $h; $y++ ) {
		$raw .= "\x00" . str_repeat( "\x30\x40\x60", $w );
	}

	return "\x89PNG\r\n\x1a\n"
		. $chunk( 'IHDR', pack( 'NNCCCCC', $w, $h, 8, 2, 0, 0, 0 ) )
		. $chunk( 'IDAT', gzcompress( $raw ) )
		. $chunk( 'IEND', '' );
};

file_put_contents( $workdir . '/sprite.png', $png( 320, 90 ) );

$html = $renderer->render(
	array(
		'src'        => 'https://cdn.example.com/clip.mp4',
		'storyboard' => './board.vtt',
	)
);

$page = <<<HTML
<!doctype html><html><head><meta charset="utf-8">
<link rel="stylesheet" href="./style-frontend.css">
<style>html,body{margin:0}</style>
</head><body>
{$html}
<script>
/*
 * Every request the page makes, so the claim that nothing is fetched before a
 * pointer touches the bar is checked rather than asserted.
 */
window.__fetched = [];

var realFetch = window.fetch;

window.fetch = function (input) {
	window.__fetched.push(String(input && input.url ? input.url : input));

	return realFetch.apply(this, arguments);
};

// A duration, so the pointer position maps to a time.
Object.defineProperty(HTMLMediaElement.prototype, 'duration', {
	get: function () { return 100; },
	configurable: true
});

window.imaginaPlayer = { restUrl: '', lazyInit: false, maxComputeBytes: 0, assetUrl: './', i18n: {} };
</script>
<script src="./frontend.js"></script>
</body></html>
HTML;

$probe = <<<'JS'
<script>
function boardRequests() {
	return window.__fetched.filter(function (u) { return u.indexOf('board.vtt') > -1; }).length;
}

setTimeout(function () {
	var seek = document.querySelector('.imgp__seek');
	var out = { beforeHover: boardRequests(), seekFound: !!seek };
	var box = seek.getBoundingClientRect();

	function hover(fraction) {
		seek.dispatchEvent(new PointerEvent('pointermove', {
			bubbles: true,
			clientX: box.left + box.width * fraction,
			clientY: box.top + box.height / 2
		}));
	}

	// Three quarters along: past the second tile's start of fifty seconds.
	hover(0.75);

	setTimeout(function () {
		out.afterHover = boardRequests();

		hover(0.75);

		setTimeout(function () {
			var preview = document.querySelector('.imgp__preview');

			out.shown = !!preview && !preview.hidden;
			out.style = preview
				? {
						position: preview.style.backgroundPosition,
						width: preview.style.width,
						image: preview.style.backgroundImage
				  }
				: null;

			// Twice hovered, still one request: the file is read once.
			hover(0.1);

			setTimeout(function () {
				var p = document.querySelector('.imgp__preview');

				out.requestsAfterTwo = boardRequests();
				out.earlyPosition = p ? p.style.backgroundPosition : null;

				seek.dispatchEvent(new PointerEvent('pointerleave', { bubbles: true }));

				setTimeout(function () {
					out.hiddenOnLeave = !!p && p.hidden;

					var pre = document.createElement('pre');
					pre.textContent = 'RESULT:' + JSON.stringify(out);
					document.body.appendChild(pre);
				}, 200);
			}, 400);
		}, 500);
	}, 600);
}, 900);
</script>
JS;

$file = $workdir . '/board.html';
file_put_contents( $file, str_replace( '</body></html>', $probe . '</body></html>', $page ) );

$dom = (string) shell_exec(
	sprintf(
		'%s --headless=new --no-sandbox --disable-gpu --allow-file-access-from-files --window-size=900,600 --virtual-time-budget=12000 --dump-dom %s 2>/dev/null',
		escapeshellarg( $browser ),
		escapeshellarg( 'file://' . $file )
	)
);

exec( 'rm -rf ' . escapeshellarg( $workdir ) );

if ( ! preg_match( '/RESULT:(\{.*?\})</s', $dom, $matches ) ) {
	check( 'the page reported', false, 'no result' );
	echo PHP_EOL . "{$failures} FAILURE(S)" . PHP_EOL;
	exit( 1 );
}

$r = json_decode( $matches[1], true );

check( 'nothing is fetched before a pointer touches the bar', 0 === (int) ( $r['beforeHover'] ?? -1 ), (string) ( $r['beforeHover'] ?? '?' ) );
check( 'and the file is read once a pointer does', 1 === (int) ( $r['afterHover'] ?? 0 ), (string) ( $r['afterHover'] ?? '?' ) );
check( 'and only once, however much it moves', 1 === (int) ( $r['requestsAfterTwo'] ?? 0 ), (string) ( $r['requestsAfterTwo'] ?? '?' ) );

echo PHP_EOL . '# And it shows the right still' . PHP_EOL;

check( 'a still appears under the pointer', true === ( $r['shown'] ?? false ) );

$style = (array) ( $r['style'] ?? array() );

check( 'sized to the tile', '160px' === ( $style['width'] ?? '' ), (string) ( $style['width'] ?? '' ) );
check( 'from the sprite beside the storyboard', str_contains( (string) ( $style['image'] ?? '' ), 'sprite.png' ), (string) ( $style['image'] ?? '' ) );

/*
 * Seventy-five seconds into a hundred-second video is the second tile, which
 * begins 160 pixels along the sprite. Getting this wrong shows the wrong
 * moment, which is worse than showing nothing.
 */
check( 'and it is the tile for that moment', '-160px 0px' === ( $style['position'] ?? '' ), (string) ( $style['position'] ?? '' ) );

check( 'moving back to the start shows the first tile', '0px 0px' === ( $r['earlyPosition'] ?? '' ), (string) ( $r['earlyPosition'] ?? '' ) );
check( 'and it goes away when the pointer leaves', true === ( $r['hiddenOnLeave'] ?? false ) );

echo PHP_EOL . ( $failures ? "{$failures} FAILURE(S)" : 'All checks passed.' ) . PHP_EOL;
exit( $failures ? 1 : 0 );
